spring:
  application:
    name: roteiro

server:
  port: 8080
  servlet:
    context-path: /api

# Configuração do OpenAI
openai:
  api:
    key: OPENAI_API_KEY
  #model: gpt-4
  model: gpt-3.5-turbo

replicate:
  api:
    key: REPLICATE_API_KEY
  #model: stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b
  model: black-forest-labs/flux-schnell:latest


# Diretório para armazenamento de arquivos gerados
file:
  output:
    path: ./gerados

# Configuração de logging
logging:
  level:
    dev.luisoliveira.roteiro: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/roteiro.log
    max-size: 10MB
    max-history: 7

# Configuração do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized