spring:
  application:
    name: roteiro
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: roteiro
      auto-index-creation: true
      uuid-representation: standard
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non-null
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /api

# Configuração do OpenAI
openai:
  api:
    key: ${OPENAI_API_KEY:chave_não_definida}
  #model: gpt-4
  model: gpt-3.5-turbo

# Configuração da ElevenLabs
elevenlabs:
  api:
    key: ${ELEVENLABS_API_KEY:chave_não_definida}
    url: https://api.elevenlabs.io/v1
  voice:
   # david_trailer: TxGEqnHWrfWFTfGW9XjX
    david_trailer: ZQe5CZNOzWyzPSCn5a3c

# Configuração do Replicate
replicate:
  api:
    key: ${REPLICATE_API_KEY:chave_não_definida}

# Configuração de geração de áudio
audio:
  generation:
    enabled: false

# Diretório para armazenamento de arquivos gerados
file:
  output:
    path: ./gerados

# Configuração de logging
logging:
  level:
    dev.luisoliveira.roteiro: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/roteiro.log
    max-size: 10MB
    max-history: 7

# Configuração do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Configuração de TTL para conteúdos
app:
  mongodb:
    content-expiry-days: 7
    cleanup-schedule: "0 0 2 * * ?"  # Executar limpeza às 2h da manhã todos os dias